const state = {
  ko: {
    chinafood: '중국식품',
    food: '식품',
    cart: '장바구니',
    deliver: '배송',
    myinfo: '내정보',
    search: '검색',
    change: '변경',
    del: '삭제',
    changeaddrinfo: '주소 수정',
    defaultaddr: '기본 배송지',
    changedefaultaddr: '배송지 변경',
    addrname: '주소 이름',
    recipient: '수령인',
    tel: '전화번호',
    postcode: '우편번호',
    addr: '주소',
    registernewaddr: '신규 주소 등록',
    confirmchangedefault: '이 배송지로 변경하시겠습니까?',
    confirmchangeaddrinfo: '이 주소지 정보를 변경하시겠습니까?',
    confirmdeleteaddr: '이 주소를 삭제하시겠습니까?',
    confirm: '확인',
    cancel: '취소',
    errpassword: '비밀번호가 맞지 않습니다.',
    err: '오류',
    password: '비밀번호',
    essential: '필수 입력',
    identity: '아이디',
    confirmpassword: '비밀번호 확인',
    changepassword: '비밀번호 변경',
    changemyinfo: '수정',
    name: '이름',
    shippingnum: '운송장번호',
    prepareproduct: '상품준비중',
    deliverlevel1: '주문을 확인하는대로 상품을 준비해서 배송하도록 하겠습니다.',
    moving: '상품이동중',
    deliverlevel2:
      '상품을 배송업체에 전달했습니다. 2,3일 사이에 고객님께 배송될 예정입니다.',
    arrivalresion: '배송지도착',
    deliverlevel3: '집 근처 배송지에 도착했습니다. 조금만 더 기다려주세요.',
    deliverstart: '배송출발',
    deliverlevel5:
      '고객님 집 근처 배송지에서 출발했습니다. 곧 고객님께 전달될 예정입니다.',
    delivercomplete: '배송완료',
    deliverlevel6: '드디어 도착했습니다! 잘 받으시길 바랍니다!',
    notice: '알림',
    signupcomplete: '회원가입 완료했습니다.',
    signup: '회원가입',
    idhint: '계정 아이디',
    namehint: '배송 받을 분의 성함',
    passwordhint: '길이8-12자,대문자,소문자,숫자,특수기호 필수',
    matchpassword: '비밀번호 일치확인',
    matchpasswordhint: '비밀번호 일치',
    telhint: '배송 받을 분의 전화번호',
    licenseterms: 'I accept the license and terms',
    licensewarning: 'You need to accept the license and terms first',
    submitted: '제출완료',
    category: '종류',
    productname: '상품명',
    flavorandspec: '규격/풍미',
    unitprice: '단가',
    sellprice: '가격',
    gocounter: '결제하기',
    lookaround: '닫기',
    shopingcart: '장바구니',
    deletecomplete: '더이상 제거할 게 없습니다.',
    receiveaddr: '배송주소',
    addrresister: '주소 등록',
    orderlist: '장바구니 상품',
    noordernotice: '장바구니에 상품을 추가해주세요.',
    foodprice: '상품가격',
    delivercost: '배송비',
    delivercostnotice: '3만원이상 무료배송',
    point: '포인트',
    total: '총합',
    checkout: '결제',
    loginnotice: ' 로그인 되었습니다.',
    logincomplete: '님, 이미 로그인 상태입니다.',
    forgetpw: '비밀번호 찾기',
    login: '로그인',
    wrongpw: '비밀번호가 틀렸습니다.',
  },
  cn: {
    chinafood: '中国食品',
    food: '食品',
    cart: '收银台',
    deliver: '运送',
    myinfo: '个人信息',
    search: '搜索',
    change: '变更',
    del: '删除',
    changeaddrinfo: '变更地址信息',
    defaultaddr: '送货地址',
    changedefaultaddr: '勾选此地址',
    addrname: '地址名称',
    recipient: '收件人',
    tel: '手机',
    postcode: '邮政编码',
    addr: '地址',
    registernewaddr: '登录新地址',
    confirmchangedefault: '确实要变更该地址为基本送货地址吗？',
    confirmchangeaddrinfo: '要变更该地址信息吗？',
    confirmdeleteaddr: '要删除该地址吗？',
    confirm: '确认',
    cancel: '取消',
    errpassword: '密码输入错误',
    err: '错误',
    password: '密码',
    essential: '必需',
    identity: '账号',
    confirmpassword: '确认密码',
    changepassword: '更改密码',
    changemyinfo: '更改信息',
    name: '姓名',
    shippingnum: '快递单号',
    prepareproduct: '发货准备中',
    deliverlevel1: '我们将尽快确认订单并抓紧给您发货。',
    moving: '高速货运中',
    deliverlevel2: '我们将商品交给了快递员，大概2,3天内您就能收到。',
    arrivalresion: '已到附近',
    deliverlevel3: '已到达附近中转站，就快到了。',
    deliverstart: '即将送到',
    deliverlevel5: '附近快递员出发了，即将送到！',
    delivercomplete: '运送完毕',
    deliverlevel6: '终于到了！愿带给你快乐！',
    notice: '提醒',
    signupcomplete: '注册成功！',
    signup: '注册',
    idhint: '输入账号',
    namehint: '收件人姓名',
    passwordhint: '密码长度8-12字，并包含：大写，小写，数字，特殊记号',
    matchpassword: '再次确认密码',
    matchpasswordhint: '再次输入相同密码',
    telhint: '收件人手机',
    licenseterms: ' I accept the license and terms',
    licensewarning: ' You need to accept the license and terms first',
    submitted: '成功递交',
    category: '种类',
    productname: '名称',
    flavorandspec: '规格/风味',
    unitprice: '单价',
    sellprice: '价格',
    gocounter: '前往收银台',
    lookaround: '再逛逛',
    shopingcart: '购物车',
    deletecomplete: '已卸完',
    receiveaddr: '送货地址',
    addrresister: '登录地址',
    orderlist: '购物车物品',
    noordernotice: '购物车里空无一物',
    foodprice: '食品价格',
    delivercost: '运送费',
    delivercostnotice: '满3万，免运费',
    point: '积分',
    total: '总计',
    checkout: '结算',
    loginnotice: ' 成功登录',
    logincomplete: '已登录',
    forgetpw: '找回密码',
    login: '登录',
    wrongpw: '密码错误',
  },
  status: null,
};

const actions = {
  setcnAction({commit, state}) {
    commit('setStatus', state.cn);
  },
  setkoAction({commit, state}) {
    commit('setStatus', state.ko);
  },
};
const mutations = {
  setStatus(state, item) {
    state.status = item;
  },
};
export default {
  namespaced: true,

  state,
  actions,
  mutations,
};
