const _ko = {
  chinafood: '중국식품',
  food: '식품',
  couter: '계산대',
  deliver: '배송',
  myinfo: '내정보',
  search: '검색',
  change: '변경',
  del: '삭제',
  changeaddrinfo: '주소 수정',
  defaultaddr: '기본 배송지',
  changedefaultaddr: '배송지 변경',
  addrname: '주소 이름',
  recipient: '수령인',
  tel: '전화번호',
  postcode: '우편번호',
  addr: '주소',
  registernewaddr: '신규 주소 등록',
  confirmchangedefault: '이 배송지로 변경하시겠습니까?',
  confirmchangeaddrinfo: '이 주소지 정보를 변경하시겠습니까?',
  confirmdeleteaddr: '이 주소를 삭제하시겠습니까?',
  confirm: '확인',
  cancel: '취소',
  errpassword: '비밀번호가 맞지 않습니다.',
  err: '오류',
  password: '비밀번호',
  essential: '필수 입력',
  identity: '아이디',
  confirmpassword: '비밀번호 확인',
  changepassword: '비밀번호 변경',
  changemyinfo: '수정',
  name: '이름',
  shippingnum: '운송장번호',
  prepareproduct: '상품준비중',
  deliverlevel1: '주문을 확인하는대로 상품을 준비해서 배송하도록 하겠습니다.',
  moving: '상품이동중',
  deliverlevel2:
    '상품을 배송업체에 전달했습니다. 2,3일 사이에 고객님께 배송될 예정입니다.',
  arrivalresion: '배송지도착',
  deliverlevel3: '집 근처 배송지에 도착했습니다. 조금만 더 기다려주세요.',
  deliverstart: '배송출발',
  deliverlevel5:
    '고객님 집 근처 배송지에서 출발했습니다. 곧 고객님께 전달될 예정입니다.',
  delivercomplete: '배송완료',
  deliverlevel6: '드디어 도착했습니다! 잘 받으시길 바랍니다!',
  notice: '알림',
  signupcomplete: '회원가입 완료했습니다.',
  signup: '회원가입',
  idhint:
    '6-12자의 영문으로 추가해주세요. 중복ID가 예상될 경우 숫자를 추가해주세요.',
  namehint: '사용자의 실제 성함을 적어주세요. 비밀번호 찾는데에 도움됩니다.',
  passwordhint: '8-16자의 영문과 숫자로 설정해주세요.',
  matchpassword: '비밀번호 일치확인',
  matchpasswordhint: '위의 비밀번호와 동일하게 입력하셔야 합니다.',
  telhint: '배송 받을 분의 전화번호',
  licenseterms: 'I accept the license and terms',
  licensewarning: 'You need to accept the license and terms first',
  submitted: '제출완료',
  category: '종류',
  productname: '상품명',
  flavorandspec: '규격/풍미',
  unitprice: '단가',
  sellprice: '가격',
  gocounter: '결제하기',
  lookaround: '닫기',
  shopingcart: '장바구니',
  deletecomplete: '더이상 제거할 게 없습니다.',
  receiveaddr: '배송주소',
  addrresister: '주소 등록',
  orderlist: '장바구니 상품',
  noordernotice: '장바구니에 상품을 추가해주세요.',
  foodprice: '상품가격',
  delivercost: '배송비',
  delivercostnotice: '3만원이상 무료',
  point: '포인트',
  total: '총합',
  checkout: '결제',
  loginnotice: ' 로그인 되었습니다.',
  logincomplete: '님, 이미 로그인 상태입니다.',
  forgetpw: '비밀번호 찾기',
  login: '로그인',
  wrongpw: '비밀번호가 틀렸습니다.',
  nodeliverinvoice: '아직 송장번호가 입력되지 않았습니다.',
  quantity: '수량',
  detailorder: '주문정보',
  tracedeliver: '배송조회',
  delivercompany: '배송사',
  ordertime: '주문시간',
  orderdate: '주문날짜',
  ordergroup: '주문번호',
  noselectaddrnotice: '배송지로 선택된 주소가 없습니다.',
  gotologinvue: '로그인하러가기',
  nologinwarning: '로그인하시고 결제해주세요.',
  changepw: '비밀번호 변경',
  oldpw: '기존 비밀번호',
  inputoldpw: '변경 전 비밀번호를 입력해주세요.',
  inputnewpw: '신규 비밀번호',
  reinput: '다시 입력',
  changepwsuccess: '비밀번호 변경이 완료되었습니다.',
  changemyinfosuccess: '정보 변경이 완료되었습니다.',
  postcodeandhint: '우편번호 (자동)',
  postcoderegister: '우편번호 찾기',
  addrandhint: '주소 (자동)',
  addrdetailandhint: '상세주소 (자동)',
  addrextraandhint: '추가 (동,호,공동현관비밀번호 등)',
  addrtagandhint: '주소별칭 (집,회사,친정집 등)',
  recipientphone: '받는 분의 전화번호',
  defaultaddr: '상세주소',
  addrresistersuccess: '배송지 등록이 완료되었습니다.',
  needloginfirst: '로그인이 필요합니다.',
  addrchangesuccess: '배송지 정보가 변경되었습니다.',
  gotodeliveryinfovue: '주문 현황 보기',
  gobackorderlistinfovue: '돌아가기',
  paymentfail: '결제에 실패하였습니다...',
  paymentsuccess: '주문이 완료되었습니다.',
  won: '원',
  won000: '천원',
  needselectedaddr: '배송지 정보가 필요합니다.',
  claim_title: '교환/환불 요청',
  claim_boy:
    '(010)8492-0526 저에게 문자 또는 전화주세요. 반드시 확인하겠습니다. 서비스 개선을 위해서 제가 어떤 문제가 발생했는지 알아야 하기 때문에 꼭 저에게 전화주세요!',
  forget_pw_title: '비밀번호 찾기',
  forget_pw_body:
    '(010)8492-0526 저에게 연락주시면 비밀번호를 초기화하여 빠르게 대응하여 신규 초기화 비밀번호를 보내드리겠습니다.',

  auto_input: '자동입력',
  coupon_info: '쿠폰 정보',
  coupon_use_info:
    '쿠폰 사용 안내: 쿠폰은 조건에 맞으면 자동으로 사용하게 됩니다.',
  coupon_use_condition:
    '쿠폰 사용 조건 안내: 상품 구매 금액만 3만원 또는 5만원 초과하면 사용할 수 있습니다.',
  use_reserve: '사용예정',
  use_condition: '사용조건: ',
  more: '이상',
  use_limit: '사용기한: ',
  up_to: '까지',
  coupon_name_none: '쿠폰 이름 (현재 보유 중인 쿠폰이 없습니다.)',
  coupon_value_none: '쿠폰 금액',
  deliver_info_title: '배송안내',
  deliver_info_text: '최근 2주간 주문이 없습니다.',
  claim: '교환/환불',
  claim_info: '교환/반품 안내',
  bundle_count: '개입',
  stock_enough: '충분', //充足
  stock_null: '곧 내림', //即将下架
  n_plus_one: '증정', //赠
  shelf_life: '유통기간: ', //保质期:
  month_count: '개월', //个月
  production_date: '생산날짜: ', //生产日期:
  after: ' 이후',
  confirm_delete: '이 상품을 장바구니에서 제거하시겠습니까?',
  deleted: '삭제함. (',
  event_5353_info: '5353 쿠폰 이벤트 안내',
  event_5353_detail:
    '이벤트 기간동안 구매 상품의 금액이 5만원을 초과할 경우, 3천원 쿠폰을 지급합니다. (해당 쿠폰은 5만원 이상 구매 시 사용가능합니다. 받은 후 3개월 내에 사용하셔야 합니다.)',
  product_unit: '하나', //单个
  product_bundle: '묶음', //捆绑
  duplicate_id_warning: '중복 아이디가 있어서 다른 아이디로 생성 바랍니다.',
  use_policy: '이용약관',
  privacy_policy: '개인정보취급방침',
};
const _cn = {
  chinafood: '中国食品',
  food: '食品',
  couter: '收银台',
  deliver: '运送',
  myinfo: '个人信息',
  search: '搜索',
  change: '变更',
  del: '删除',
  changeaddrinfo: '变更地址信息',
  defaultaddr: '送货地址',
  changedefaultaddr: '勾选此地址',
  addrname: '地址名称',
  recipient: '收件人',
  tel: '手机',
  postcode: '邮政编码',
  addr: '地址',
  registernewaddr: '登录新地址',
  confirmchangedefault: '确实要变更该地址为基本送货地址吗？',
  confirmchangeaddrinfo: '要变更该地址信息吗？',
  confirmdeleteaddr: '要删除该地址吗？',
  confirm: '确认',
  cancel: '取消',
  errpassword: '密码输入错误',
  err: '错误',
  password: '密码',
  essential: '必需',
  identity: '账号',
  confirmpassword: '确认密码',
  changepassword: '更改密码',
  changemyinfo: '更改信息',
  name: '姓名',
  shippingnum: '快递单号',
  prepareproduct: '发货准备中',
  deliverlevel1: '我们将尽快确认订单并抓紧给您发货。',
  moving: '高速货运中',
  deliverlevel2: '我们将商品交给了快递员，大概2,3天内您就能收到。',
  arrivalresion: '已到附近',
  deliverlevel3: '已到达附近中转站，就快到了。',
  deliverstart: '即将送到',
  deliverlevel5: '附近快递员出发了，即将送到！',
  delivercomplete: '运送完毕',
  deliverlevel6: '终于到了！愿带给你快乐！',
  notice: '提醒',
  signupcomplete: '注册成功！',
  signup: '注册',
  idhint: '请输入6-12字节的英文账号',
  namehint: '请输入真实姓名，以便用于找回密码',
  passwordhint: '请输入8-12字节的英文与数字的组合',
  matchpassword: '再次确认密码',
  matchpasswordhint: '请输入与以上相同的密码',
  telhint: '请输入收件人的手机号码',
  licenseterms: ' I accept the license and terms',
  licensewarning: ' You need to accept the license and terms first',
  submitted: '成功递交',
  category: '种类',
  productname: '名称',
  flavorandspec: '规格/风味',
  unitprice: '单价',
  sellprice: '价格',
  gocounter: '前往收银台',
  lookaround: '再逛逛',
  shopingcart: '购物车',
  deletecomplete: '已卸完',
  receiveaddr: '送货地址',
  addrresister: '登录地址',
  orderlist: '购物车物品',
  noordernotice: '购物车里空无一物',
  foodprice: '食品价格',
  delivercost: '运送费',
  delivercostnotice: '满3万，免运费',
  point: '积分',
  total: '总计',
  checkout: '结算',
  loginnotice: ' 成功登录',
  logincomplete: '已登录',
  forgetpw: '找回密码',
  login: '登录',
  wrongpw: '密码错误',
  nodeliverinvoice: '还没有获得快递单号',
  simpledesc: '简介',
  quantity: '数量',
  detailorder: '购物清单',
  tracedeliver: '快递查询',
  delivercompany: '快递公司',
  ordertime: '购买时间',
  orderdate: '购买日期',
  ordergroup: '订单号码',
  noselectaddrnotice: '请添加送货地址信息',
  gotologinvue: '去登录',
  nologinwarning: '登录账号才可以支付',
  changepw: '变更密码',
  oldpw: '变更前密码',
  inputoldpw: '请正确输入变更前的密码',
  inputnewpw: '新密码',
  reinput: '重新输入',
  changepwsuccess: '密码更新完毕！',
  changemyinfosuccess: '信息更新完毕！',
  postcodeandhint: '邮政编码 (自动填充)',
  postcoderegister: '查询邮政编码',
  addrandhint: '地址 (自动填充)',
  addrdetailandhint: '详细地址 (自动填充)',
  addrextraandhint: '其他信息 (如，几栋几号公用大门密码)',
  addrtagandhint: '地址名称 (如，家，公司，儿子家...)',
  recipientphone: '收件人手机号',
  defaultaddr: '基本收件地址',
  addrresistersuccess: '地址登录完毕！',
  needloginfirst: '请先登录账号。',
  addrchangesuccess: '地址信息变更完毕',
  gotodeliveryinfovue: '查看订单信息',
  gobackorderlistinfovue: '返回',
  paymentfail: '支付失败...',
  paymentsuccess: '下单完毕！',
  won: '韩元',
  won000: '千韩元',
  needselectedaddr: '请先登录地址。',
  claim_title: '申请退换',
  claim_boy:
    '(010)8492-0526 为了改善服务，我必需知晓发生的问题，请一定联系或者发信息给我！',
  forget_pw_title: '申请找回密码',
  forget_pw_body: '(010)8492-0526 联系我，将尽快为您初始化新密码并通知你。',

  auto_input: '自动填充',
  coupon_info: '优惠券',
  coupon_use_info: '优惠券使用规则：满足优惠券使用条件则自动使用。',
  coupon_use_condition: '优惠券使用条件：购买金额满3万或者5万即可使用。',
  use_reserve: '使用预定',
  use_condition: '使用条件：',
  more: '以上',
  use_limit: '使用期限：',
  up_to: '截止',
  coupon_name_none: '优惠券名称（现无可用优惠券）',
  coupon_value_none: '优惠券金额',
  deliver_info_title: '运送信息',
  deliver_info_text: '近2周内没有购买记录。',
  claim: '交换|返货',
  claim_info: '交换|返货政策',
  bundle_count: '个装',
  stock_enough: '充足', //充足
  stock_null: '即将下架', //即将下架
  n_plus_one: '赠', //赠
  shelf_life: '保质期：', //保质期:
  month_count: '个月', //个月
  production_date: '生产日期：', //生产日期:
  after: '以后',
  confirm_delete: '确定要删除此商品吗？',
  deleted: '已删除。(',
  event_5353_info: '5353优惠券活动消息',
  event_5353_detail:
    '活动期间内，如购买额超过5万韩元，则赠送3千韩元优惠券！购买额超过5万韩元，即可使用该优惠券。该优惠券的使用期限为3个月。',
  product_unit: '单个', //单个
  product_bundle: '捆绑', //捆绑
  duplicate_id_warning: '重复账号。请使用其他账号。',
  use_policy: '使用条款',
  privacy_policy: '个人信息使用方针',
};

const state = {
  ko: _ko,
  cn: _cn,
  status: _cn,
};

const actions = {
  setcnAction({commit, state}) {
    commit('setStatus', state.cn);
  },
  setkoAction({commit, state}) {
    commit('setStatus', state.ko);
  },
};
const mutations = {
  setStatus(state, item) {
    state.status = item;
  },
};
export default {
  namespaced: true,

  state,
  actions,
  mutations,
};
